### ISSUE TITLE
TimeoutError when there are too many bonus

### ISSUE THREAD

**Issue by y0umu** [luoy2/pyOnmyoji#7]
I was testing party.py and occasionally found that if there were too many (3 or 4 rows of) bonus items, the script would just hang at the first `while` loop in `combat.Combat.get_result` till it timed out:

``` python
 def get_result(self):
        # wait_for_color(CombatColor.InCombat)
        win_loc = myFindColor(CombatColor.Win)
        lose_loc = myFindColor(CombatColor.Lose)
        cur_time = datetime.datetime.now()
        while not win_loc and not lose_loc:  # stuck in this loop till timeout
            win_loc = myFindColor(CombatColor.Win)
            lose_loc = myFindColor(CombatColor.Lose)
            # self.logger.debug(f'win_loc: {win_loc}; lose_loc: {lose_loc}')
            if (datetime.datetime.now() - cur_time).seconds > self.combat_time_limit:
                self.logger.debug('time out ending combat.')
                if myFindColor(CombatColor.Damo):
                    leaving_test = 0
                    while leaving_test < 3:
                        utilities.random_sleep(0.2, 0.5)
                        wait_for_leaving_color(CombatColor.Damo,
                                               max_waiting_time=15,
                                               max_click_time=8,
                                               clicking=True,
                                               clicking_gap=0.2,
                                               location=(57, 940),
                                               rand_offset=20)
                        leaving_test += 1
                    return CombatResult.WIN
                else:
                    raise TimeoutError
# not listing the rest codes
```

This is what I see from stdout (the lines reported might not correspond to master's since I added some debugging `print`s):
```
2019-02-08 20:44:01.595 INFO combat - __init__: 开始御魂战斗
2019-02-08 20:49:02.795 DEBUG combat - get_result: time out ending combat.
Traceback (most recent call last):
  File "party.py", line 72, in <module>
    as_leader('御魂', chaoguiwang=False)
  File "party.py", line 42, in as_leader
    battle_result = battle.start(auto_ready=True)
  File "D:\dev_workspace\pyOnmyoji\combat.py", line 38, in start
    return self.get_result()
  File "D:\dev_workspace\pyOnmyoji\combat.py", line 65, in get_result
    raise TimeoutError
TimeoutError
```
Meanwhile the game was just stuck at the bonus calculation page since the script was not pushing forward.

This problem is somewhat hard to repoduce since you rarely get **3 or 4 rows of bonus**.

I cannot figure out why the built-in precaution `if myFindColor(CombatColor.Damo): ...` failed either. My guess is that the coordinate of _Damo_ varies to the amount of awards you get. The colors picked in advance merely just miss the point.

**Comment by luoy2** [comment]
thanks for raising this up. I also found this problem occasionally and I found one reason is that sometimes Onmyoji just doesn’t response per click after running for a while. As you said it’s hard to reproduce but you can definitely try to change the color pick point.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
